```{r}
require(purrr)
require(hdf5r)
require(inspre)
require(ggplot2)
require(tidyr)
require(tibble)
require(dplyr)
require(readr)
require(igraph)
require(ggupset)
require(betareg)
require(expm)
require(foreach)
require(doParallel)
require(stringr)
```


```{r}
data_mat_loc <- '/home/brielin/Work/inspre_gwps_data/data_mats'
rdata_loc <- '/home/brielin/Work/inspre_gwps_data/saved_rdata'
k562_norm_sc_fn <- paste0(data_mat_loc, '/K562_essential_normalized_singlecell_01.h5ad')
save_dag_res <- paste0(rdata_loc, '/gwps_res_dag.Rdata')
save_guide_res <- paste0(rdata_loc, '/gwps_guide_data.Rdata')
save_gene_data <- paste0(rdata_loc, '/gene_data.Rdata')
save_graph_data <- paste0(rdata_loc, '/gwps_graph_data.Rdata')
annot_MM_loc <- paste0(data_mat_loc, '/GeneAnnotation_MM.tsv')
annot_JM_loc <- paste0(data_mat_loc, '/MorrisScience2023_SupplementaryTable_refGeneAnnotations.txt')
cis_trans_loc <- paste0(rdata_loc,'/cis_trans.csv')
```


```{r}
min_nz <- 0.03/2
load(save_dag_res)
# best_lambda <- which.min(res_dag$eps_hat_G)
best_lambda <- 6 # Big drop in eps_hat_R, good rho_G, largest D_hat > 0.01
R_hat <- res_dag$R_hat
SE_hat <- res_dag$SE_hat
G_hat <- res_dag$G_hat[,,best_lambda]
G_hat[abs(c(G_hat)) < min_nz] <- 0
U_hat <- res_dag$U[,,best_lambda]
V_hat <- res_dag$V[,,best_lambda]
H_hat <- U_hat * diag(V_hat)

hfile_sc <- hdf5r::H5File$new(k562_norm_sc_fn, "r")
var <- inspre::parse_hdf5_df(hfile_sc, 'var')

load(save_guide_res)
```


```{r}
genes <- colnames(G_hat)
rownames(R_hat) <- genes
rownames(G_hat) <- genes
rownames(U_hat) <- genes
colnames(U_hat) <- genes

R_long <- tidyr::pivot_longer(tibble::as_tibble(R_hat, rownames="Exposure"), -Exposure,
                              names_to="Outcome", values_to = "R_hat")
SE_long <- tidyr::pivot_longer(tibble::as_tibble(SE_hat, rownames="Exposure"), -Exposure,
                              names_to="Outcome", values_to = "SE_hat")
G_long <- tidyr::pivot_longer(tibble::as_tibble(G_hat, rownames="Exposure"), -Exposure,
                              names_to="Outcome", values_to = "G_hat")
U_long <- tidyr::pivot_longer(tibble::as_tibble(U_hat, rownames = "Exposure"), -Exposure,
                              names_to = "Outcome", values_to = "U_hat")
graph_data <- R_long
graph_data$SE_hat <- SE_long$SE_hat
graph_data$G_hat <- G_long$G_hat
graph_data$U_hat <- U_long$U_hat

graph_data <- graph_data %>%
  dplyr::mutate(Z = R_hat/SE_hat, p = 2*(1-pnorm(abs(Z))), p_fdr = p.adjust(p, method='fdr'))
```


```{r, fig.widith=3.25, fig.height=3.25}
plot_order <- hclust(dist(U_hat))$order

graph_data <- dplyr::mutate(graph_data, R_plot=if_else(Exposure==Outcome, 0, R_hat), U_plot=if_else(Exposure==Outcome, 0, U_hat)) 
```


```{r, fig.width=3.5, fig.asp=1}
ggplot(graph_data, aes(y=Exposure, x=Outcome)) + # geom_tile(aes(fill=R_plot)) +
  geom_raster(aes(fill=sign(R_plot)*sqrt(abs(R_plot)))) +
  scale_x_discrete(limits = genes[(plot_order)], labels = NULL) +
  scale_y_discrete(limits = genes[rev(plot_order)], labels = NULL) +
  scale_fill_gradient2(limits = c(-1, 1))  +
  labs(x = NULL, y = "Exposure", title = "Observed marginal ACE (R)") +
  theme(plot.title = element_text(size=10), axis.ticks=element_blank(),
        axis.title = element_text(size=10), legend.title = element_text(size=10),
        plot.margin = unit(c(0.5,0.5,0.5,0.5), 'mm')) +
  guides(fill=FALSE) + coord_fixed()
ggsave("plots/R_hat.png")
```


```{r, fig.width=3.5, fig.asp=1}
ggplot(graph_data, aes(y=Exposure, x=Outcome)) + # geom_tile(aes(fill=U_plot)) +
  geom_raster(aes(fill=sign(U_hat)*sqrt(abs(U_hat)))) +
  scale_x_discrete(limits = genes[(plot_order)], labels = NULL) +
  scale_y_discrete(limits = genes[rev(plot_order)], labels = NULL) +
  scale_fill_gradient2(limits = c(-1, 1))  +
  labs(x = NULL, y = "Exposure", title = "Shrunk marginal ACE (U)") +
  theme(plot.title = element_text(size=10), axis.ticks=element_blank(),
        axis.title = element_text(size=10), legend.title = element_text(size=10),
        plot.margin = unit(c(0.5,0.5,0.5,0.5), 'mm')) +
  guides(fill=FALSE) + coord_fixed()
ggsave("plots/U_hat.png")
```


```{r, fig.width=4.25, fig.asp=0.9}
ggplot(graph_data, aes(y=Exposure, x=Outcome)) + # geom_tile(aes(fill=G_hat)) + 
  geom_tile(aes(fill=sign(G_hat)*sqrt(abs(G_hat)))) +
  scale_x_discrete(limits = genes[(plot_order)], labels = NULL) +
  scale_y_discrete(limits = genes[rev(plot_order)], labels = NULL) +
  scale_fill_gradient2(limits = c(-1, 1)) + #, breaks = c(-1, 0, 1)) +
  labs(x = "Outcome", y = "Exposure", fill = "Effect", title = "Inferred direct causal effect (G)") +
  theme(plot.title = element_text(size=10), axis.ticks=element_blank(),
        axis.title = element_text(size=10), legend.title = element_text(size=9),
        legend.key.size = unit(0.4, 'cm'), legend.text = element_text(size=9),
        plot.margin = unit(c(0.5,0,0.5,0.5), 'mm')) +
  coord_fixed()
ggsave("plots/G_hat.png")
```


```{r}
gene_data <- as_tibble_col(genes, column_name = "gene")
gene_data <- gene_data %>% dplyr::left_join(
  select(var, gene_id, gene_name, cv, mean, std), by=c("gene" = "gene_id")) %>%
  dplyr::left_join(select(guide_effects, target, inst_beta, inst_cor, n), by=c("gene"="target"))
gene_data <- gene_data %>% dplyr::left_join(enframe(genes[plot_order], name="order", value="gene"), by="gene")
```


```{r}
scale_factor <- 2
# graph <- make_igraph(G_hat, min_edge_value = 0.05, scale_factor = scale_factor)
graph <- make_igraph(G_hat, min_edge_value = 0.015, scale_factor = scale_factor)

distances <- igraph::distances(graph, mode = "out")
distances_long <- tidyr::pivot_longer(
  as_tibble(distances, rownames = "Exposure"), -Exposure,
  names_to = "Outcome", values_to = "log_scale_dist")

graph_data$G_path_scaled <- 1/exp(distances_long$log_scale_dist)
# graph_data$path_length <- purrr::pmap_int(
for_path <- graph_data %>% filter(G_path_scaled > 0) %>% select(Exposure, Outcome, G_path_scaled)

for_path$path <- purrr::pmap(
  for_path,
  function(Exposure, Outcome, G_path_scaled){
    # split <- strsplit(Exposure, "_", fixed=TRUE)
    # as.integer(ifelse(G_path > 0, length(igraph::shortest_paths(graph, split[[1]][length(split[[1]])], Outcome, mode = "out")$vpath[[1]]) - 1, NA))
    # as.integer(ifelse(G_path_scaled > 0, length(igraph::shortest_paths(graph, Exposure, Outcome, mode = "out")$vpath[[1]]) - 1, NA))
    names(igraph::shortest_paths(graph, Exposure, Outcome, mode = "out")$vpath[[1]])
  }
)

graph_data <- dplyr::left_join(select(graph_data, -G_path_scaled), for_path, by = c("Exposure", "Outcome"))
graph_data$path_length <- map_int(graph_data$path, ~ length(.x)-1)
graph_data$path_length <- ifelse(graph_data$path_length==-1, NA, graph_data$path_length)
graph_data <- graph_data %>% dplyr::mutate(G_path = ifelse(G_path_scaled > 0, G_path_scaled*(scale_factor**path_length), 0),
                       eff_explained = ifelse((Exposure != Outcome) & (G_path > 0), abs(G_path/U_hat), NA))
gene_data$out_deg <- igraph::degree(graph, mode = "out")[gene_data$gene]
gene_data$in_deg <- igraph::degree(graph, mode = "in")[gene_data$gene]
gene_data$deg <- igraph::degree(graph, mode = "all")[gene_data$gene]
gene_data$bt_centrality <- igraph::betweenness(graph, normalized = TRUE)
gene_data$eg_centrality <- igraph::eigen_centrality(graph)$vector
```


```{r}
save(gene_data, file=save_gene_data)
save(graph_data, file=save_graph_data)
```


```{r}
load(save_gene_data)
load(save_graph_data)
```


```{r, fig.height=2.5, fig.width=4}
# graph_data %>% filter(!is.na(path_length), Exposure != Outcome) %>%
#   ggplot(aes(x=path_length)) + geom_bar(aes(y=..count../sum(..count..))) +
#   labs( title = "Shortest path between nodes (all)", x = "Path length", y = "Proportion") + 
#   theme_classic() +
#   theme(plot.title = element_text(size=10),  axis.title = element_text(size=10)) +
#   scale_x_continuous(breaks = scales::pretty_breaks(n=6))
  
graph_data %>% filter(!is.na(path_length), Exposure != Outcome, p_fdr < 0.05) %>%
  ggplot(aes(x=path_length)) + geom_bar(aes(y=..count../sum(..count..))) +
  labs( title = "Shortest path between nodes", x = "Path length", y = "Proportion") + 
  theme_classic() +
  theme(plot.title = element_text(size=10), axis.title = element_text(size=10)) +
#        axis.ticks.y = element_blank(), axis.text.y=element_blank()) +
  scale_x_continuous(breaks = scales::pretty_breaks(n=6))
ggsave("plots/shortest_path.png")


gene_data %>% ggplot(aes(x = in_deg)) + geom_histogram() + 
  labs(x = "In-degree", y = "Count", title = "In-degree distribution") +
  theme_classic() + theme(plot.title = element_text(size=10), axis.title = element_text(size=10))
ggsave("plots/in_degree.png")

gene_data %>% ggplot(aes(x = out_deg)) + geom_histogram() + 
  labs( x = "Out-degree", y = "Count", title = "Out-degree distribution") +
  theme_classic() + theme(plot.title = element_text(size=10), axis.title = element_text(size=10))
ggsave("plots/out_degree.png")

gene_data %>% ggplot(aes(eg_centrality)) + geom_density()

tibble(Percentage=seq(0,1,0.01), Quantile=quantile(gene_data$eg_centrality, seq(0,1,0.01))) %>%
  ggplot(aes(Percentage, Quantile)) + geom_line() + theme_classic() + 
  labs(title="Eigencentrality distribution") + theme(plot.title = element_text(size=10), axis.title = element_text(size=10))
ggsave("plots/eigencentrality.png")

ecdf_fn <- ecdf(gene_data$eg_centrality)
tibble(Eigencentrality=seq(0,1,0.01), Cumulative_distribution=map_dbl(seq(0,1,0.01), ecdf_fn)) %>%
ggplot(aes(Eigencentrality, Cumulative_distribution)) + geom_line() + theme_classic() + 
  labs(title="Eigencentrality CDF") + theme(plot.title = element_text(size=10), axis.title = element_text(size=10))

gene_data %>% ggplot(aes(x = eg_centrality)) + geom_histogram() + 
  labs( x = "Eigencentrality", y = "Count", title = "Eigencentrality distribution") +
  theme_classic() + theme(plot.title = element_text(size=10), axis.title = element_text(size=10))
ggsave("plots/eigencentrality.png")


print(summary(filter(graph_data, !is.na(eff_explained), p_fdr < 0.05)$eff_explained))
```


```{r, fig.height=2.5, fig.width=3.25}
graph_data %>% filter(!is.na(eff_explained), p_fdr < 0.05) %>% ggplot(aes(x=100*eff_explained)) +
  geom_histogram(aes(y=..count../sum(..count..)), bins = 50) + xlim(0, 150) +
  labs(title = "ACE explained by shortest path",
       x = "Percentage of effect explained", y = NULL) +
  theme_classic() + 
  theme(plot.title = element_text(size=10), axis.title = element_text(size=10)) + ylim(0, 0.3)
ggsave("plots/ace_explained.png")
```



```{r}
print(sum(abs(graph_data$G_hat) > 0))
print(sum(graph_data$p_fdr < 0.05, na.rm=T))
print((sum(!is.na(graph_data$path_length))-788)/(nrow(graph_data)-788))
print(mean(graph_data$path_length, na.rm=T))
print(sd(graph_data$path_length, na.rm=T))
print(sd(graph_data$path_length, na.rm=T)/sqrt(length(graph_data$path_length)))
print(mean(filter(graph_data, p_fdr<0.05)$path_length, na.rm=T))
print(sd(filter(graph_data, p_fdr<0.05)$path_length, na.rm=T))
print(sd(filter(graph_data, p_fdr<0.05)$path_length, na.rm=T)/sqrt(nrow(filter(graph_data, p_fdr<0.05))))
print(median(filter(graph_data, p_fdr<0.05)$eff_explained, na.rm=T))
print(sum(filter(graph_data, p_fdr<0.05)$eff_explained > 1, na.rm=T))
```


```{r, fig.height=2.13, fig.width=2.8}
gene_data %>% dplyr::arrange(desc(eg_centrality)) %>% head(10) %>%
  ggplot(aes(x=reorder(gene_name, eg_centrality, decreasing = TRUE), y=eg_centrality)) + geom_col() +
  labs(x = NULL, y = "Eigencentrality", title="Highest eigencentrality genes") + 
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
        plot.title = element_text(size=10),
        axis.title = element_text(size=10))

# gene_data %>% dplyr::arrange(desc(bt_centrality)) %>% head() %>% ggplot(aes(x=gene_name, y=bt_centrality)) + geom_col() + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
# gene_data %>% dplyr::arrange(desc(out_deg)) %>% head() %>% ggplot(aes(x=gene_name, y=out_deg)) + geom_col() + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
# gene_data %>% dplyr::arrange(desc(deg)) %>% head() %>% ggplot(aes(x=gene_name, y=deg)) + geom_col() + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```


```{r}
gene_annotations_MM <- readr::read_delim(annot_MM_loc)
gene_annotations_JM <- readr::read_delim(annot_JM_loc)

gene_data <- gene_data %>% dplyr::left_join(gene_annotations_MM, by=c("gene_name" ="gene"))
gene_data <- gene_data %>% dplyr::left_join(gene_annotations_JM, by=c("gene_name" ="gene"))
gene_data <- mutate(gene_data, eg_cent_mod = if_else(
  eg_centrality==1, 0.999, if_else(eg_centrality==0, 0.001, eg_centrality)))
gene_data <- mutate(gene_data, bt_cent_mod = if_else(
  bt_centrality==1, 0.999, if_else(bt_centrality==0, 0.001, bt_centrality)))
```


```{r}
# Source utility.R
all_beta_res <- purrr::map(colnames(gene_annotations_MM)[2:17], ~ calc_beta_res(.x, gene_data))
MM_annot_res <- purrr::map(all_beta_res, get_coeff) %>% list_rbind()
names(all_beta_res) <- colnames(gene_annotations_MM)[2:17]
MM_annot_res$p_adj <- p.adjust(MM_annot_res$Pr...z.., method='holm')
# readr::write_csv(MM_annot_res, file = "/gpfs/commons/groups/knowles_lab/gwps/saved_rdata/mm_annot_res.csv")
MM_annot_res %>% arrange(p_adj)
```

```{r, fig.width=3.4, fig.height=2.5}
line_data = data.frame(x=seq(0, 1, .01), y=predict(all_beta_res$gnomAD_pLI, newdata = data.frame(gnomAD_pLI=seq(0, 1, .01))))
gene_data %>% ggplot(aes(x=gnomAD_pLI, y=eg_centrality)) + geom_point(size=0.5) +
  geom_line(data=line_data, aes(x=x, y=y), color='blue', linewidth=1) + theme_classic() + ylab('Eigencentrality')
ggsave("plots/pli.png")

```


```{r, fig.width=2.7, fig.height=2}
# Plotting significant relationships

# NOTE PLI (prob of loss of function intolerance) is anticorrelated to LOEUF in MM annot

line_data = data.frame(x=seq(0, 7500, 1), y=predict(all_beta_res$n_ppis, newdata = data.frame(n_ppis=seq(0, 7500, 1))))
gene_data %>% ggplot(aes(x=n_ppis, y=eg_centrality)) + geom_point(alpha=0.2) +
  geom_line(data=line_data, aes(x=x, y=y), color='blue', linewidth=1)  + theme_classic() + ylab('Eigencentrality')
ggsave("plots/n_ppis_supp.png")

line_data = data.frame(x=seq(0, 1, .01), y=predict(all_beta_res$gnomAD_pLI, newdata = data.frame(gnomAD_pLI=seq(0, 1, .01))))
gene_data %>% ggplot(aes(x=gnomAD_pLI, y=eg_centrality)) + geom_point(alpha=0.2) +
  geom_line(data=line_data, aes(x=x, y=y), color='blue', linewidth=1) + theme_classic() + ylab('Eigencentrality')
ggsave("plots/pli_supp.png")

line_data = data.frame(x=seq(0, 0.64, .01), y=predict(all_beta_res$sHet, newdata = data.frame(sHet=seq(0, 0.64, .01))))
gene_data %>% ggplot(aes(x=sHet, y=eg_centrality)) + geom_point(alpha=0.2) +
  geom_line(data=line_data, aes(x=x, y=y), color='blue', linewidth=1) + theme_classic() + ylab('Eigencentrality')
ggsave("plots/shet_supp.png")

line_data = data.frame(x=seq(0, 1, .01), y=predict(all_beta_res$HI_Index, newdata = data.frame(HI_Index=seq(0, 1, .01))))
gene_data %>% ggplot(aes(x=HI_Index, y=eg_centrality)) + geom_point(alpha=0.2) +
  geom_line(data=line_data, aes(x=x, y=y), color='blue', linewidth=1) + theme_classic() + ylab('Eigencentrality')
ggsave("plots/hi_index_supp.png")

line_data = data.frame(x=seq(0, 1, .01), y=predict(all_beta_res$pHaplo, newdata = data.frame(pHaplo=seq(0, 1, .01))))
gene_data %>% ggplot(aes(x=pHaplo, y=eg_centrality)) + geom_point(alpha=0.2) +
  geom_line(data=line_data, aes(x=x, y=y), color='blue', linewidth=1) + theme_classic() + ylab('Eigencentrality')
ggsave("plots/phaplo_supp.png")

line_data = data.frame(x=seq(0, 2, .01), y=predict(all_beta_res$gnomAD_LOEUF, newdata = data.frame(gnomAD_LOEUF=seq(0, 2, .01))))
gene_data %>% ggplot(aes(x=gnomAD_LOEUF, y=eg_centrality)) + geom_point(alpha=0.2) +
  geom_line(data=line_data, aes(x=x, y=y), color='blue', linewidth=1) + theme_classic() + ylab('Eigencentrality')
ggsave("plots/loeuf_supp.png")

line_data = data.frame(x=seq(0, 2, .01), y=predict(all_beta_res$gnomAD_MisOEUF, newdata = data.frame(gnomAD_MisOEUF=seq(0, 2, .01))))
gene_data %>% ggplot(aes(x=gnomAD_MisOEUF, y=eg_centrality)) + geom_point(alpha=0.2) +
  geom_line(data=line_data, aes(x=x, y=y), color='blue', linewidth=1) + theme_classic() + ylab('Eigencentrality')
ggsave("plots/misoeuf_supp.png")
```


```{r}
# Variance explained analyses
D <- nrow(gene_data)
U_hat <- t(matrix(graph_data$U_hat, nrow=D, ncol=D))
rownames(U_hat) <- gene_data$gene
colnames(U_hat) <- gene_data$gene

s2 <- est_noise_var(U_hat, rep(1,D), non_neg = TRUE)
beta2_adj = ((U_hat-diag(D))**2)
R_adj = beta2_adj*s2

v_exp_in <- colSums(R_adj)
v_exp_by <- rowSums(R_adj)
gene_data$v_exp_in <- v_exp_in
gene_data$v_exp_by <- v_exp_by

cis_trans <- readr::read_csv(cis_trans_loc)

gene_data <- dplyr::left_join(gene_data, cis_trans, by = dplyr::join_by(gene == Gene))
```


```{r, fig.width=3.85, fig.height=2.5}
calc_r_se <- function(.x, n_samp=1000){
  data <- dplyr::filter(gene_data, v_exp_in > .x, gw_h2 > .x) %>%
    dplyr::select(gene, v_exp_in, gw_h2)
  cors <- rep(0, nrow(data))
  for(i in 1:n_samp){
    resample <- sample(nrow(data), nrow(data), replace=T)
    resample_data <- data[resample, ]
    cors[i] <- cor(resample_data$v_exp_in, resample_data$gw_h2)
  }
  res <- data.frame(cors=cors)
  res$cutoff <- .x
  return(res)
}

plot_data <- purrr::map(seq(0, 0.5, .05), calc_r_se) %>% purrr::list_rbind()
plot_data %>% ggplot(aes(factor(cutoff), cors)) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
  geom_jitter(width=0.1, alpha=0.05, size=0.01) + 
  theme_classic() +
  labs(x="Minimum h2", y="Bootstrap correlation", title="Cor of gene h2 with graph variance explained") +
  theme(plot.title = element_text(size=10, hjust=1), axis.title = element_text(size=10))
ggsave("plots/h2.png")
```


```{r}
# Re-estimating r2 in shuffled or non-shuffled data
D <- nrow(gene_data)
ntc = 'non-targeting'
hfile_sc <- hdf5r::H5File$new(k562_norm_sc_fn, "r")
var <- inspre::parse_hdf5_df(hfile_sc, 'var')
obs <- inspre::parse_hdf5_df(hfile_sc, 'obs')
cells_ntc <- obs$gene == ntc
# TODO: fix this eg use_genes <- var$gene_id %in% gene_data$gene
X_all <- hfile_sc[['X']][,]
rownames(X_all) <- var$gene_id
X_all <- X_all[gene_data$gene, ]
X_ntc <- X_all[,cells_ntc]

G_hat <- t(matrix(graph_data$G_hat, nrow=D, ncol=D))
rownames(G_hat) <- gene_data$gene
colnames(G_hat) <- gene_data$gene

calc_r2 <- function(G, gene, X_ntc, X_all, obs){
  G_test <- G[, gene]
  nzgenes <- names(G_test[abs(G_test) > 0])
  grab_genes <- c(gene, nzgenes)

  cells_eff <- obs$gene_id %in% nzgenes
  X_ntc_sub <- X_ntc[grab_genes, ]
  X_eff <- X_all[grab_genes, cells_eff]

  X_design <- cbind(X_ntc_sub, X_eff)
  res <- summary(lm(X_design[1,] ~ t(X_design[2:length(grab_genes), ]) + 0))$r.squared
  
  return(data.frame(gene = gene, r2 = res, row.names=gene))
}

calc_r2_rand <- function(G, gene, X_ntc, X_all, obs){
  G_test <- G[, gene]
  nzgenes <- names(G_test[abs(G_test) > 0])
  grab_genes <- c(gene, sample(setdiff(colnames(G), c(gene, nzgenes)), length(nzgenes)))
  
  cells_eff <- obs$gene_id %in% nzgenes
  X_ntc_sub <- X_ntc[grab_genes, ]
  X_eff <- X_all[grab_genes, cells_eff]

  X_design <- cbind(X_ntc_sub, X_eff)
  res <- summary(lm(X_design[1,] ~ t(X_design[2:length(grab_genes), ]) + 0))$r.squared
  return(data.frame(gene = gene, r2 = res, row.names=gene))
}

shuffle_r2 <- function(res, G, X_ntc, X_all, obs, shuffle = 0){
  cat(paste0("Shuffle iter: ", shuffle, "\n"))
  G_shuff <- G
  if(shuffle > 0){
    permutation <- sample(nrow(G), nrow(G))
    rownames(G_shuff) <- rownames(G)[permutation]
    colnames(G_shuff) <- colnames(G)[permutation]
  }
  shuff_res <- purrr::map(colnames(G_shuff), ~ calc_r2(G_shuff, .x, X_ntc, X_all, obs)) %>%
    purrr::list_rbind()
  return(shuff_res[res$gene,]$r2)
}

G_res <- purrr::map(colnames(G_hat), ~ calc_r2(G_hat, .x, X_ntc, X_all, obs)) %>% purrr::list_rbind()

n_shuff <- 10000
perm_res <- foreach::foreach(i=1:n_shuff, .combine=cbind) %dopar%
  shuffle_r2(G_res, G_hat, X_ntc, X_all, obs, i)

rand_res <- foreach::foreach(i=1:n_shuff, .combine=cbind) %dopar% {
  rand_ve <- purrr::map(colnames(G_hat), ~ calc_r2_rand(G_hat, .x, X_ntc, X_all, obs)) %>% purrr::list_rbind()
  rand_ve[G_res$gene,]$r2
}

# Calculate p-val for total variance explained
alpha_p <- 0.01
z_a <- qnorm(1-alpha_p)
p_G_r2 <- mean(mean(G_res$r2) < colMeans(perm_res))
ci_naive <- z_a*sqrt((p_G_r2*(1-p_G_r2))/n_shuff)
p_G_r2_lo_naive <- p_G_r2 - ci_naive
p_G_r2_hi_naive <- p_G_r2 + ci_naive
pm <- (z_a/(2*n_shuff))*sqrt(4*n_shuff*p_G_r2*(1-p_G_r2) + z_a**2)
p_G_r2_lo <- (1/(1+z_a**2/n_shuff))*(p_G_r2 + z_a**2/(2*n_shuff) - pm)
p_G_r2_hi <- (1/(1+z_a**2/n_shuff))*(p_G_r2 + z_a**2/(2*n_shuff) + pm)
G_res$p_G_r2 <- p_G_r2
G_res$p_G_r2_lo <- p_G_r2_lo
G_res$p_G_r2_hi <- p_G_r2_hi

# Calculate p-val per gene
G_res$p_gene_r2 <- rowMeans(G_res$r2 < perm_res)
ci_naive <- z_a*sqrt((G_res$p_gene_r2*(1 - G_res$p_gene_r2))/n_shuff)
G_res$p_lo_naive <- G_res$p_gene_r2 - ci_naive
G_res$p_hi_naive <- G_res$p_gene_r2 + ci_naive
pm <- (z_a/(2*n_shuff))*sqrt(4*n_shuff*G_res$p_gene_r2*(1-G_res$p_gene_r2) + z_a**2)
G_res$p_lo <- (1/(1+z_a**2/n_shuff))*(G_res$p_gene_r2 + z_a**2/(2*n_shuff) - pm)
G_res$p_hi <- (1/(1+z_a**2/n_shuff))*(G_res$p_gene_r2 + z_a**2/(2*n_shuff) + pm)
G_res$p_fdr <- p.adjust(G_res$p_gene_r2, method='fdr')

# Calculate p-val per gene (random edges)
G_res$p_gene_r2_edge <- rowMeans(G_res$r2 < rand_res)
ci_naive <- z_a*sqrt((G_res$p_gene_r2_edge*(1 - G_res$p_gene_r2_edge))/n_shuff)
G_res$p_lo_naive_edge <- G_res$p_gene_r2_edge - ci_naive
G_res$p_hi_naive_edge_<- G_res$p_gene_r2_edge + ci_naive
pm <- (z_a/(2*n_shuff))*sqrt(4*n_shuff*G_res$p_gene_r2_edge*(1-G_res$p_gene_r2_edge) + z_a**2)
G_res$p_lo_edge <- (1/(1+z_a**2/n_shuff))*(G_res$p_gene_r2_edge + z_a**2/(2*n_shuff) - pm)
G_res$p_hi_edge <- (1/(1+z_a**2/n_shuff))*(G_res$p_gene_r2_edge + z_a**2/(2*n_shuff) + pm)
G_res$p_fdr_edge <- p.adjust(G_res$p_gene_r2_edge, method='fdr')

save(perm_res, file='/gpfs/commons/groups/knowles_lab/gwps/saved_rdata/perm_res.Rdata')
save(rand_res, file='/gpfs/commons/groups/knowles_lab/gwps/saved_rdata/rand_res.Rdata')
save(G_res, file='/gpfs/commons/groups/knowles_lab/gwps/saved_rdata/G_res.Rdata')
```


```{r}
load(paste0(rdata_loc, '/G_res.Rdata'))
load(paste0(rdata_loc, '/perm_res.Rdata'))
load(paste0(rdata_loc,'/rand_res.Rdata'))
```


```{r, fig.width=3.4, fig.height=2.5}
# Could correlate with CRISPR n_cells, effect size, etc
plot_fdr <- tibble(fdr = seq(0.01, 1, 0.01), num_genes = purrr::map_int(seq(0.01, 1, 0.01), ~ sum(G_res$p_fdr < .x)))
plot_fdr %>% ggplot(aes(fdr, num_genes)) + geom_line() + theme_classic() +
  labs(x="FDR", y="Number signif genes", title="Genes with signif var exp by the network\n Essential screen network and data") +
  theme(plot.title = element_text(size=10, hjust=1), axis.title = element_text(size=10))
ggsave("plots/var_exp.png")

plot_density <- tibble(r2_perm = colMeans(perm_res))
plot_density %>% ggplot(aes(r2_perm)) + geom_density() + geom_vline(xintercept = mean(G_res$r2))

plot_qq(dat=-log10(G_res$p_gene_r2), dist=function(.x) -log10(.x), kind = 'one-sided', decreasing=TRUE) + theme_classic() +
  labs(title="Genes with signif var exp by the network\n Essential screen network and data") +
  theme(plot.title = element_text(size=10, hjust=1), axis.title = element_text(size=10))
ggsave("plots/var_exp_qq.png")

tibble(null_cor=rowMeans(perm_res), eg_centrality=gene_data$eg_centrality) %>% 
  ggplot(aes(null_cor, eg_centrality)) + geom_point() + theme_classic() +
  labs(x="Var exp by random graphs", y="Eigencentrality") +
  geom_smooth(method='lm', formula="y~x+0")
ggsave("plots/null_var_eg.png")


plot_fdr_edge <- tibble(fdr = seq(0.01, 1, 0.01), num_genes = purrr::map_int(seq(0.01, 1, 0.01), ~ sum(G_res$p_fdr_edge < .x)))
plot_fdr_edge %>% ggplot(aes(fdr, num_genes)) + geom_line() + theme_classic() +
  labs(x="FDR", y="Number signif genes", title="Genes with signif var exp by the network\n Essential screen network and data") +
  theme(plot.title = element_text(size=10, hjust=1), axis.title = element_text(size=10))
ggsave("plots/var_exp_appeal.png")

plot_qq(dat=-log10(G_res$p_gene_r2_edge), dist=function(.x) -log10(.x), kind = 'one-sided', decreasing=TRUE) + theme_classic() +
  labs(title="Genes with signif var exp by the network\n Essential screen network and data") +
  theme(plot.title = element_text(size=10, hjust=1), axis.title = element_text(size=10))
ggsave("plots/var_exp_qq_appeal.png")

tibble(null_cor=rowMeans(rand_res), eg_centrality=gene_data$eg_centrality) %>% 
  ggplot(aes(null_cor, eg_centrality)) + geom_point() + theme_classic() +
  labs(x="Var exp by random genes", y="Eigencentrality") +
  geom_smooth(method='lm', formula="y~x+0")
ggsave("plots/null_var_appeal.png")

```


```{r, fig.height=2, fig.width=3}
gene_data$p_fdr <- G_res$p_fdr
gene_data %>% ggplot(aes(p_fdr, inst_beta)) + geom_point() + theme_classic() + theme(axis.title = element_text(size=10))
ggsave("plots/supp_fdr_beta.png")
gene_data %>% ggplot(aes(p_fdr, n)) + geom_point() + theme_classic() + theme(axis.title = element_text(size=10))
ggsave("plots/supp_fdr_n.png")
gene_data %>% ggplot(aes(p_fdr, out_deg)) + geom_point() + theme_classic() + theme(axis.title = element_text(size=10))
ggsave("plots/supp_fdr_out.png")
gene_data %>% ggplot(aes(p_fdr, in_deg)) + geom_point() + theme_classic() + theme(axis.title = element_text(size=10))
ggsave("plots/supp_fdr_in.png")
```


```{r, fig.height=2, fig.width=3}
gene_data$p_fdr_edge <- G_res$p_fdr_edge
gene_data %>% ggplot(aes(p_fdr_edge, inst_beta)) + geom_point() + theme_classic() + theme(axis.title = element_text(size=10))
# ggsave("plots/supp_fdr_beta.png")
gene_data %>% ggplot(aes(p_fdr_edge, n)) + geom_point() + theme_classic() + theme(axis.title = element_text(size=10))
# ggsave("plots/supp_fdr_n.png")
gene_data %>% ggplot(aes(p_fdr_edge, out_deg)) + geom_point() + theme_classic() + theme(axis.title = element_text(size=10))
# ggsave("plots/supp_fdr_out.png")
gene_data %>% ggplot(aes(p_fdr_edge, in_deg)) + geom_point() + theme_classic() + theme(axis.title = element_text(size=10))
# ggsave("plots/supp_fdr_in.png")
```


```{r}
# Can we do this with wps screen?
k562_gwps_fn = '/gpfs/commons/groups/knowles_lab/gwps/data/K562_gwps_normalized_singlecell_01.h5ad'
ntc = 'non-targeting'

hfile_gwps <- hdf5r::H5File$new(k562_gwps_fn, "r")
var_gwps <- inspre::parse_hdf5_df(hfile_gwps, 'var')
obs_gwps <- inspre::parse_hdf5_df(hfile_gwps, 'obs')
cells_ntc <- obs_gwps$gene == ntc
use_genes <- var_gwps$gene_id %in% gene_data$gene
X_all <- hfile_gwps[['X']][use_genes, ]
rownames(X_all) <- var_gwps$gene_id[var_gwps$gene_id %in% gene_data$gene]

X_all <- X_all[gene_data$gene, ]
X_ntc <- X_all[,cells_ntc]

G_res_gwps <- purrr::map(colnames(G_hat), ~ calc_r2(G_hat, .x, X_ntc, X_all, obs_gwps)) %>% purrr::list_rbind()


n_shuff <- 10000
perm_res_gwps <- foreach::foreach(i=1:n_shuff, .combine=cbind) %dopar%
  shuffle_r2(G_res_gwps, G_hat, X_ntc, X_all, obs_gwps, i)

rand_res_gwps <- foreach::foreach(i=1:n_shuff, .combine=cbind) %dopar% {
  rand_ve <- purrr::map(colnames(G_hat), ~ calc_r2_rand(G_hat, .x, X_ntc, X_all, obs_gwps)) %>% purrr::list_rbind()
  rand_ve[G_res_gwps$gene,]$r2
}

# Calculate p-val for total variance explained
alpha_p <- 0.01
z_a <- qnorm(1-alpha_p)
p_G_r2 <- mean(mean(G_res_gwps$r2) < colMeans(perm_res_gwps))
ci_naive <- z_a*sqrt((p_G_r2*(1-p_G_r2))/n_shuff)
p_G_r2_lo_naive <- p_G_r2 - ci_naive
p_G_r2_hi_naive <- p_G_r2 + ci_naive
pm <- (z_a/(2*n_shuff))*sqrt(4*n_shuff*p_G_r2*(1-p_G_r2) + z_a**2)
p_G_r2_lo <- (1/(1+z_a**2/n_shuff))*(p_G_r2 + z_a**2/(2*n_shuff) - pm)
p_G_r2_hi <- (1/(1+z_a**2/n_shuff))*(p_G_r2 + z_a**2/(2*n_shuff) + pm)
G_res_gwps$p_G_r2 <- p_G_r2
G_res_gwps$p_G_r2_lo <- p_G_r2_lo
G_res_gwps$p_G_r2_hi <- p_G_r2_hi

# Calculate p-val per gene
G_res_gwps$p_gene_r2 <- rowMeans(G_res_gwps$r2 < perm_res_gwps)
ci_naive <- z_a*sqrt((G_res_gwps$p_gene_r2*(1 - G_res_gwps$p_gene_r2))/n_shuff)
G_res_gwps$p_lo_naive <- G_res_gwps$p_gene_r2 - ci_naive
G_res_gwps$p_hi_naive <- G_res_gwps$p_gene_r2 + ci_naive
pm <- (z_a/(2*n_shuff))*sqrt(4*n_shuff*G_res_gwps$p_gene_r2*(1-G_res_gwps$p_gene_r2) + z_a**2)
G_res_gwps$p_lo <- (1/(1+z_a**2/n_shuff))*(G_res_gwps$p_gene_r2 + z_a**2/(2*n_shuff) - pm)
G_res_gwps$p_hi <- (1/(1+z_a**2/n_shuff))*(G_res_gwps$p_gene_r2 + z_a**2/(2*n_shuff) + pm)
G_res_gwps$p_fdr <- p.adjust(G_res_gwps$p_gene_r2, method='fdr')

# Calculate p-val per gene (random edges)
G_res_gwps$p_gene_r2_edge <- rowMeans(G_res_gwps$r2 < rand_res_gwps)
ci_naive <- z_a*sqrt((G_res_gwps$p_gene_r2_edge*(1 - G_res_gwps$p_gene_r2_edge))/n_shuff)
G_res_gwps$p_lo_naive_edge <- G_res_gwps$p_gene_r2_edge - ci_naive
G_res_gwps$p_hi_naive_edge_<- G_res_gwps$p_gene_r2_edge + ci_naive
pm <- (z_a/(2*n_shuff))*sqrt(4*n_shuff*G_res_gwps$p_gene_r2_edge*(1-G_res_gwps$p_gene_r2_edge) + z_a**2)
G_res_gwps$p_lo_edge <- (1/(1+z_a**2/n_shuff))*(G_res_gwps$p_gene_r2_edge + z_a**2/(2*n_shuff) - pm)
G_res_gwps$p_hi_edge <- (1/(1+z_a**2/n_shuff))*(G_res_gwps$p_gene_r2_edge + z_a**2/(2*n_shuff) + pm)
G_res_gwps$p_fdr_edge <- p.adjust(G_res_gwps$p_gene_r2_edge, method='fdr')

save(perm_res_gwps, file='/gpfs/commons/groups/knowles_lab/gwps/saved_rdata/perm_res_gwps.Rdata')
save(rand_res_gwps, file='/gpfs/commons/groups/knowles_lab/gwps/saved_rdata/rand_res_gwps.Rdata')
save(G_res_gwps, file='/gpfs/commons/groups/knowles_lab/gwps/saved_rdata/G_res_gwps.Rdata')
```


```{r}
load(paste0(rdata_loc, '/G_res_gwps.Rdata'))
load(paste0(rdata_loc, '/perm_res_gwps.Rdata'))
load(paste0(rdata_loc,'/rand_res_gwps_1.Rdata'))
```


```{r, fig.width=3.4, fig.height=2.5}
plot_fdr <- tibble(fdr = seq(0.01, 1, 0.01), num_genes = purrr::map_int(seq(0.01, 1, 0.01), ~ sum(G_res_gwps$p_fdr < .x)))
plot_fdr %>% ggplot(aes(fdr, num_genes)) + geom_line() + theme_classic() +
  labs(x="FDR", y="Number signif genes", title="Genes with signif var exp by the network\n Ess screen network, GW screen data") +
  theme(plot.title = element_text(size=10, hjust=1), axis.title = element_text(size=10))
ggsave("plots/var_exp_gwps.png")

plot_density <- tibble(r2_perm = colMeans(perm_res_gwps))
plot_density %>% ggplot(aes(r2_perm)) + geom_density() + geom_vline(xintercept = mean(G_res_gwps$r2))

plot_qq(dat=-log10(G_res_gwps$p_gene_r2), dist=function(.x) -log10(.x), kind = 'one-sided', decreasing=TRUE) + theme_classic() +
  labs(title="Genes with signif var exp by the network\n Ess screen network, GW screen data") +
  theme(plot.title = element_text(size=10, hjust=1), axis.title = element_text(size=10))
ggsave("plots/var_exp_qq_gwps.png")

plot_fdr <- tibble(fdr = seq(0.01, 1, 0.01), num_genes = purrr::map_int(seq(0.01, 1, 0.01), ~ sum(G_res_gwps$p_fdr_edge < .x)))
plot_fdr %>% ggplot(aes(fdr, num_genes)) + geom_line() + theme_classic() +
  labs(x="FDR", y="Number signif genes", title="Genes with signif var exp by the network\n Ess screen network, GW screen data") +
  theme(plot.title = element_text(size=10, hjust=1), axis.title = element_text(size=10))
ggsave("plots/var_exp_gwps_appeal.png")

plot_qq(dat=-log10(G_res_gwps$p_gene_r2_edge), dist=function(.x) -log10(.x), kind = 'one-sided', decreasing=TRUE) + theme_classic() +
  labs(title="Genes with signif var exp by the network\n Ess screen network, GW screen data") +
  theme(plot.title = element_text(size=10, hjust=1), axis.title = element_text(size=10))
ggsave("plots/var_exp_qq_gwps_appeal.png")

```


```{r}
cv_dag_fn <- paste0(rdata_loc, '/gwps_res_dag_cv.Rdata')
load(cv_dag_fn)
best_lambda <- 6 
min_nz = 0.03/2
G_hat <- res_dag$G_hat[,,best_lambda]
G_hat[abs(c(G_hat)) < min_nz] <- 0

CV_G_1 <- res_dag$CV_G_1[,,best_lambda]
CV_G_1[abs(c(CV_G_1)) < min_nz] <- 0
CV_G_2 <- res_dag$CV_G_2[,,best_lambda]
CV_G_2[abs(c(CV_G_2)) < min_nz] <- 0
CV_G_3 <- res_dag$CV_G_3[,,best_lambda]
CV_G_3[abs(c(CV_G_3)) < min_nz] <- 0
CV_G_4 <- res_dag$CV_G_4[,,best_lambda]
CV_G_4[abs(c(CV_G_4)) < min_nz] <- 0
CV_G_5 <- res_dag$CV_G_5[,,best_lambda]
CV_G_5[abs(c(CV_G_5)) < min_nz] <- 0
CV_mean <- (res_dag$xi_mat[,,6] > 0.5)*(sign(CV_G_1+CV_G_2+CV_G_3+CV_G_4+CV_G_5))
```


```{r}
all_mats = list(G_hat, CV_mean, CV_G_1, CV_G_2, CV_G_3, CV_G_4, CV_G_5)
purrr::map(all_mats, \(x) purrr::map_dbl(all_mats, \(y) calc_metrics(x, y)$F1))
purrr::map(all_mats, \(x) purrr::map_dbl(all_mats, \(y) calc_metrics(x, y)$weight_acc))
```


```{r}
k562_norm_sc_fn_gwps = '/gpfs/commons/groups/knowles_lab/gwps/data/K562_gwps_normalized_singlecell_01.h5ad'
save_dag_res_gwps = '/gpfs/commons/groups/knowles_lab/gwps/saved_rdata/gwps_all_res_dag.Rdata'
save_guide_res_gwps = '/gpfs/commons/groups/knowles_lab/gwps/saved_rdata/gwps_all_guide_data.Rdata'
save_gene_data_gwps = '/gpfs/commons/groups/knowles_lab/gwps/saved_rdata/gene_all_data.Rdata'
save_graph_data_gwps = '/gpfs/commons/groups/knowles_lab/gwps/saved_rdata/gwps_all_graph_data.Rdata'
```


```{r}
min_nz <- 0.03/2
load(save_dag_res_gwps)
# best_lambda <- which.min(res_dag$eps_hat_G)
best_lambda <- 7 # largest D_hat > 0.01
R_hat_gwps <- res_dag$R_hat
SE_hat_gwps <- res_dag$SE_hat
G_hat_gwps <- res_dag$G_hat[,,best_lambda]
G_hat_gwps[abs(c(G_hat_gwps)) < min_nz] <- 0
U_hat_gwps <- res_dag$U[,,best_lambda]
V_hat_gwps <- res_dag$V[,,best_lambda]
H_hat_gwps <- U_hat * diag(V_hat)

hfile_sc_gwps <- hdf5r::H5File$new(k562_norm_sc_fn_gwps, "r")
var_gwps <- inspre::parse_hdf5_df(hfile_sc_gwps, 'var')

load(save_guide_res_gwps)
```


```{r}
genes_gwps <- colnames(G_hat_gwps)
rownames(R_hat_gwps) <- genes_gwps
rownames(G_hat_gwps) <- genes_gwps
rownames(U_hat_gwps) <- genes_gwps
colnames(U_hat_gwps) <- genes_gwps

R_long_gwps <- tidyr::pivot_longer(tibble::as_tibble(R_hat_gwps, rownames="Exposure"), -Exposure,
                              names_to="Outcome", values_to = "R_hat")
SE_long_gwps <- tidyr::pivot_longer(tibble::as_tibble(SE_hat_gwps, rownames="Exposure"), -Exposure,
                              names_to="Outcome", values_to = "SE_hat")
G_long_gwps <- tidyr::pivot_longer(tibble::as_tibble(G_hat_gwps, rownames="Exposure"), -Exposure,
                              names_to="Outcome", values_to = "G_hat")
U_long_gwps <- tidyr::pivot_longer(tibble::as_tibble(U_hat_gwps, rownames = "Exposure"), -Exposure,
                              names_to = "Outcome", values_to = "U_hat")
graph_data_gwps <- R_long_gwps
graph_data_gwps$SE_hat <- SE_long_gwps$SE_hat
graph_data_gwps$G_hat <- G_long_gwps$G_hat
graph_data_gwps$U_hat <- U_long_gwps$U_hat

graph_data_gwps <- graph_data_gwps %>%
  dplyr::mutate(Z = R_hat/SE_hat, p = 2*(1-pnorm(abs(Z))), p_fdr = p.adjust(p, method='fdr'))
```


```{r}
gene_data_gwps <- as_tibble_col(genes_gwps, column_name = "gene")
gene_data_gwps <- gene_data_gwps %>% dplyr::left_join(
  select(var_gwps, gene_id, gene_name, cv, mean, std), by=c("gene" = "gene_id")) # %>%
  # dplyr::left_join(select(guide_effects_gwps, target, inst_beta, inst_cor, n), by=c("gene"="target"))
# gene_data_gwps <- gene_data %>% dplyr::left_join(enframe(genes[plot_order], name="order", value="gene"), by="gene")
```


```{r}
scale_factor <- 2
# graph <- make_igraph(G_hat, min_edge_value = 0.05, scale_factor = scale_factor)
graph_gwps <- make_igraph(G_hat_gwps, min_edge_value = 0.015, scale_factor = scale_factor)

distances_gwps <- igraph::distances(graph_gwps, mode = "out")
distances_long_gwps <- tidyr::pivot_longer(
  as_tibble(distances_gwps, rownames = "Exposure"), -Exposure,
  names_to = "Outcome", values_to = "log_scale_dist")

graph_data_gwps$G_path_scaled <- 1/exp(distances_long_gwps$log_scale_dist)
# graph_data$path_length <- purrr::pmap_int(
for_path <- graph_data_gwps %>% filter(G_path_scaled > 0) %>% select(Exposure, Outcome, G_path_scaled)

for_path$path <- purrr::pmap(
  for_path,
  function(Exposure, Outcome, G_path_scaled){
    # split <- strsplit(Exposure, "_", fixed=TRUE)
    # as.integer(ifelse(G_path > 0, length(igraph::shortest_paths(graph, split[[1]][length(split[[1]])], Outcome, mode = "out")$vpath[[1]]) - 1, NA))
    # as.integer(ifelse(G_path_scaled > 0, length(igraph::shortest_paths(graph, Exposure, Outcome, mode = "out")$vpath[[1]]) - 1, NA))
    names(igraph::shortest_paths(graph_gwps, Exposure, Outcome, mode = "out")$vpath[[1]])
  }
)

graph_data_gwps <- dplyr::left_join(select(graph_data_gwps, -G_path_scaled), for_path, by = c("Exposure", "Outcome"))
graph_data_gwps$path_length <- map_int(graph_data_gwps$path, ~ length(.x)-1)
graph_data_gwps$path_length <- ifelse(graph_data_gwps$path_length==-1, NA, graph_data_gwps$path_length)
graph_data_gwps <- graph_data_gwps %>% dplyr::mutate(G_path = ifelse(G_path_scaled > 0, G_path_scaled*(scale_factor**path_length), 0),
                       eff_explained = ifelse((Exposure != Outcome) & (G_path > 0), abs(G_path/U_hat), NA))
gene_data_gwps$out_deg <- igraph::degree(graph_gwps, mode = "out")[gene_data_gwps$gene]
gene_data_gwps$in_deg <- igraph::degree(graph_gwps, mode = "in")[gene_data_gwps$gene]
gene_data_gwps$deg <- igraph::degree(graph_gwps, mode = "all")[gene_data_gwps$gene]
gene_data_gwps$bt_centrality <- igraph::betweenness(graph_gwps, normalized = TRUE)
gene_data_gwps$eg_centrality <- igraph::eigen_centrality(graph_gwps)$vector


gene_data_gwps <- gene_data_gwps %>% dplyr::left_join(gene_annotations_JM, by=c("gene_name" ="gene"))
gene_data_gwps <- gene_data_gwps %>% dplyr::left_join(gene_annotations_MM, by=c("gene_name" ="gene"))
gene_data_gwps <- mutate(gene_data_gwps, eg_cent_mod = if_else(
  eg_centrality==1, 0.999, if_else(eg_centrality==0, 0.001, eg_centrality)))
gene_data <- mutate(gene_data, bt_cent_mod = if_else(
  bt_centrality==1, 0.999, if_else(bt_centrality==0, 0.001, bt_centrality)))

save(gene_data_gwps, file=save_gene_data_gwps)
save(graph_data_gwps, file=save_graph_data_gwps)
```


```{r}
load(save_graph_data_gwps)
load(save_gene_data_gwps)
```

```{r, fig.width=2.7, fig.height=2}
graph_data_gwps %>% filter(!is.na(path_length), Exposure != Outcome, p_fdr < 0.05) %>%
  ggplot(aes(x=path_length)) + geom_bar(aes(y=..count../sum(..count..))) +
  labs( title = "Shortest path between nodes", x = "Path length", y = "Proportion") + 
  theme_classic() +
  theme(plot.title = element_text(size=10), axis.title = element_text(size=10)) +
#        axis.ticks.y = element_blank(), axis.text.y=element_blank()) +
  scale_x_continuous(breaks = scales::pretty_breaks(n=6))
ggsave("plots/shortest_path_gwps.png")


graph_data_gwps %>% filter(!is.na(eff_explained), p_fdr < 0.05) %>% ggplot(aes(x=100*eff_explained)) +
  geom_histogram(aes(y=..count../sum(..count..)), bins = 50) + xlim(0, 150) +
  labs(title = "ACE explained by shortest path",
       x = "Percentage of effect explained", y = NULL) +
  theme_classic() + 
  theme(plot.title = element_text(size=10), axis.title = element_text(size=10)) + ylim(0, 0.3)
ggsave("plots/ace_explained_gwps.png")

gene_data_gwps %>% ggplot(aes(x = in_deg)) + geom_histogram() + 
  labs(x = "In-degree", y = "Count", title = "In-degree distribution") +
  theme_classic() + theme(plot.title = element_text(size=10), axis.title = element_text(size=10))
ggsave("plots/in_degree_gwps.png")

gene_data_gwps %>% ggplot(aes(x = out_deg)) + geom_histogram() + 
  labs( x = "Out-degree", y = "Count", title = "Out-degree distribution") +
  theme_classic() + theme(plot.title = element_text(size=10), axis.title = element_text(size=10))
ggsave("plots/out_degree_gwps.png")

gene_data_gwps %>% ggplot(aes(x = eg_centrality)) + geom_histogram() + 
  labs( x = "Eigencentrality", y = "Count", title = "Eigencentrality distribution") +
  theme_classic() + theme(plot.title = element_text(size=10), axis.title = element_text(size=10))
ggsave("plots/eigencentrality_gwps.png")
```


```{r}
all_beta_res_gwps <- purrr::map(colnames(gene_annotations_MM)[2:17], ~ calc_beta_res(.x, gene_data_gwps))
MM_annot_res_gwps <- purrr::map(all_beta_res, get_coeff) %>% list_rbind()
names(all_beta_res_gwps) <- colnames(gene_annotations_MM)[2:17]
# MM_annot_res_gwps$p_adj <- p.adjust(MM_annot_res$Pr...z.., method='holm')
# readr::write_csv(MM_annot_res, file = "/gpfs/commons/groups/knowles_lab/gwps/saved_rdata/mm_annot_res.csv")
MM_annot_res_gwps # %>% arrange(p_adj)
```



```{r, fig.width=3.4, fig.height=2.5}
line_data = data.frame(x=seq(0, 1, .01), y=predict(all_beta_res_gwps$gnomAD_pLI, newdata = data.frame(gnomAD_pLI=seq(0, 1, .01))))
gene_data_gwps %>% ggplot(aes(x=gnomAD_pLI, y=eg_centrality)) + geom_point(size=0.5) +
  geom_line(data=line_data, aes(x=x, y=y), color='blue', linewidth=1) + theme_classic() + ylab('GW Net Eigencentrality')
ggsave("plots/pli_gwps.png")

```


```{r, fig.width=2.7, fig.height=2}
line_data = data.frame(x=seq(0, 7500, 1), y=predict(all_beta_res_gwps$n_ppis, newdata = data.frame(n_ppis=seq(0, 7500, 1))))
gene_data_gwps %>% ggplot(aes(x=n_ppis, y=eg_centrality)) + geom_point() +
  geom_line(data=line_data, aes(x=x, y=y), color='blue', linewidth=1)  + theme_classic() + ylab('Eigencentrality')
ggsave("plots/n_ppis_gwps_supp.png")

line_data = data.frame(x=seq(0, 1, .01), y=predict(all_beta_res_gwps$gnomAD_pLI, newdata = data.frame(gnomAD_pLI=seq(0, 1, .01))))
gene_data_gwps %>% ggplot(aes(x=gnomAD_pLI, y=eg_centrality)) + geom_point() +
  geom_line(data=line_data, aes(x=x, y=y), color='blue', linewidth=1) + theme_classic() + ylab('Eigencentrality')
ggsave("plots/pli_gwps_supp.png")

line_data = data.frame(x=seq(0, 0.64, .01), y=predict(all_beta_res_gwps$sHet, newdata = data.frame(sHet=seq(0, 0.64, .01))))
gene_data_gwps %>% ggplot(aes(x=sHet, y=eg_centrality)) + geom_point() +
  geom_line(data=line_data, aes(x=x, y=y), color='blue', linewidth=1) + theme_classic() + ylab('Eigencentrality')
ggsave("plots/shet_gwps_supp.png")

line_data = data.frame(x=seq(0, 1, .01), y=predict(all_beta_res_gwps$HI_Index, newdata = data.frame(HI_Index=seq(0, 1, .01))))
gene_data_gwps %>% ggplot(aes(x=HI_Index, y=eg_centrality)) + geom_point() +
  geom_line(data=line_data, aes(x=x, y=y), color='blue', linewidth=1) + theme_classic() + ylab('Eigencentrality')
ggsave("plots/hi_gwps_index_supp.png")

line_data = data.frame(x=seq(0, 1, .01), y=predict(all_beta_res_gwps$pHaplo, newdata = data.frame(pHaplo=seq(0, 1, .01))))
gene_data_gwps %>% ggplot(aes(x=pHaplo, y=eg_centrality)) + geom_point() +
  geom_line(data=line_data, aes(x=x, y=y), color='blue', linewidth=1) + theme_classic() + ylab('Eigencentrality')
ggsave("plots/phaplo_gwps_supp.png")

line_data = data.frame(x=seq(0, 2, .01), y=predict(all_beta_res_gwps$gnomAD_LOEUF, newdata = data.frame(gnomAD_LOEUF=seq(0, 2, .01))))
gene_data_gwps %>% ggplot(aes(x=gnomAD_LOEUF, y=eg_centrality)) + geom_point() +
  geom_line(data=line_data, aes(x=x, y=y), color='blue', linewidth=1) + theme_classic() + ylab('Eigencentrality')
ggsave("plots/loeuf_gwps_supp.png")

line_data = data.frame(x=seq(0, 2, .01), y=predict(all_beta_res_gwps$gnomAD_MisOEUF, newdata = data.frame(gnomAD_MisOEUF=seq(0, 2, .01))))
gene_data_gwps %>% ggplot(aes(x=gnomAD_MisOEUF, y=eg_centrality)) + geom_point() +
  geom_line(data=line_data, aes(x=x, y=y), color='blue', linewidth=1) + theme_classic() + ylab('Eigencentrality')
ggsave("plots/misoeuf_gwps_supp.png")
```



```{r}
common_genes <- intersect(rownames(G_hat), rownames(G_hat_gwps))

cor_R <- cor(c(R_hat[common_genes, common_genes]), c(R_hat_gwps[common_genes, common_genes]), use = 'pairwise.complete.obs')
cor_U <- cor(c(U_hat[common_genes, common_genes]), c(U_hat_gwps[common_genes, common_genes]), use = 'pairwise.complete.obs')
nU <- length(U_hat[common_genes, common_genes])
nR <- sum(!is.na(R_hat[common_genes, common_genes]*R_hat_gwps[common_genes, common_genes]))
sU2 <- (1-cor_U**2)/(nU-2)
sR2 <- (1-cor_R**2)/(nR-2)
t_stat <- (cor_U-cor_R)/sqrt(sU2 + sR2)
nu <- (sU2/nU + sR2/nR)**2/( sU2**2/(nU**2*(nU-1)) +  sR2**2/(nR**2*(nR-1)))
1-pt(t_stat, df=nu)
```


```{r, fig.width=3.4, fig.height=2.5}
tibble(ESS=gene_data$eg_centrality[common_genes],
       GWPS=gene_data_gwps$eg_centrality[common_genes]) %>%
  ggplot(aes(ESS, GWPS)) + geom_point() + geom_smooth(method='lm', formula = "y~x+0") +
  theme_classic() + ylab('GW Eigencentrality') + xlab('Ess Eigencentrality')
ggsave("plots/eg_comp.png")
```


```{r}
# Getting around that igraph doesn't like negative edge weights
G1 <- G_hat
G2 <- G1 %*% G_hat
G3 <- G2 %*% G_hat
G4 <- G3 %*% G_hat
G5 <- G4 %*% G_hat
G6 <- G5 %*% G_hat

G_1D <- diag(nrow(G1)) + G1
G_2D <- G_1D + G2
G_3D <- G_2D + G3
G_4D <- G_3D + G4
G_5D <- G_4D + G5
G_6D <- G_5D + G6
```


```{r}
ess_only_genes <- setdiff(rownames(G_hat), common_genes)
completions <- pmap_dbl(list(graph_data$path, graph_data$path_length, graph_data$Exposure, graph_data$Outcome),
                             function(path, path_length, Exposure, Outcome){
                               if(prod(!is.na(path_length), path_length > 1, na.rm=T)){
                                 # print(path[2:path_length])
                                 if(all(path[2:path_length] %in% ess_only_genes)){
                                   return(get(paste0("G_", path_length, "D"))[Exposure, Outcome])
                                 } else {
                                   return(0)
                                 }
                               }else{
                                 return(0)
                               }
                             }
                            )
G_comp <- G_hat + t(matrix(completions, nrow=nrow(G_hat)))
G_comp <- G_comp[common_genes, common_genes]
# completions_gwps[is.na(completions_gwps)] <- 0
```


```{r}
# Getting around that igraph doesn't like negative edge weights
G1 <- G_hat_gwps
G2 <- G1 %*% G_hat_gwps
G3 <- G2 %*% G_hat_gwps
G4 <- G3 %*% G_hat_gwps
G5 <- G4 %*% G_hat_gwps
G6 <- G5 %*% G_hat_gwps

G_1D <- diag(nrow(G1)) + G1
G_2D <- G_1D + G2
G_3D <- G_2D + G3
G_4D <- G_3D + G4
G_5D <- G_4D + G5
G_6D <- G_5D + G6
```


```{r}
graph_data_gwps$G_2D <- tidyr::pivot_longer(tibble::as_tibble(G_2D, rownames="Exposure"), -Exposure, names_to="Outcome", values_to = "G_2D")$G_2D
graph_data_gwps$G_3D <- tidyr::pivot_longer(tibble::as_tibble(G_3D, rownames="Exposure"), -Exposure, names_to="Outcome", values_to = "G_3D")$G_3D
graph_data_gwps$G_4D <- tidyr::pivot_longer(tibble::as_tibble(G_4D, rownames="Exposure"), -Exposure, names_to="Outcome", values_to = "G_4D")$G_4D
graph_data_gwps$G_5D <- tidyr::pivot_longer(tibble::as_tibble(G_5D, rownames="Exposure"), -Exposure, names_to="Outcome", values_to = "G_5D")$G_5D
graph_data_gwps$G_6D <- tidyr::pivot_longer(tibble::as_tibble(G_6D, rownames="Exposure"), -Exposure, names_to="Outcome", values_to = "G_6D")$G_6D
graph_data_gwps$G_7D <- tidyr::pivot_longer(tibble::as_tibble(G_7D, rownames="Exposure"), -Exposure, names_to="Outcome", values_to = "G_7D")$G_7D
```


```{r}
gwps_only_genes <- setdiff(rownames(G_hat_gwps), common_genes)
completions_gwps <- pmap_dbl(list(graph_data_gwps$path, graph_data_gwps$path_length, graph_data_gwps$Exposure, graph_data_gwps$Outcome),
                             function(path, path_length, Exposure, Outcome){
                               if(prod(!is.na(path_length), path_length > 1, na.rm=T)){
                                 # print(path[2:path_length])
                                 if(all(path[2:path_length] %in% gwps_only_genes)){
                                   return(get(paste0("G_", path_length, "D"))[Exposure, Outcome])
                                 } else {
                                   return(0)
                                 }
                               }else{
                                 return(0)
                               }
                             }
                            )
G_comp_gwps <- G_hat_gwps + t(matrix(completions_gwps, nrow=nrow(G_hat_gwps)))
G_comp_gwps <- G_comp_gwps[common_genes, common_genes]
# completions_gwps[is.na(completions_gwps)] <- 0
```


```{r}
calc_metrics(G_comp, G_comp_gwps, eps=0.015)
```
