```{r}
require(hdf5r)
require(caret)
require(tidyr)
require(dplyr)
require(purrr)
require(tibble)
require(ggplot2)
require(igraph)
```


```{r}
k562_norm_sc_fn = '/gpfs/commons/groups/knowles_lab/gwps/data/K562_essential_normalized_singlecell_01.h5ad'
# k562_norm_sc_fn = '/gpfs/commons/home/groups/knowles_lab/gwps/data/K562_gwps_normalized_singlecell_01.h5ad'


# At some point this gets auto-converted to 'non.targeting' by R...
ntc = 'non-targeting'
```


```{r}
hfile_sc <- H5File$new(k562_norm_sc_fn, "r")
```


```{r}
obs <- parse_hdf5_df(hfile_sc, 'obs')
var <- parse_hdf5_df(hfile_sc, 'var')
```


```{r}
genes_guides <- filter(obs, gene != ntc) %>% distinct(gene_id, gene_transcript) %>% filter(gene_id %in% var$gene_id)
cells_ntc <- obs$gene == ntc
n_ntc <- sum(cells_ntc)
X_ntc <- hfile_sc[['X']][, cells_ntc]

guide_effects <- map2(genes_guides$gene_transcript, genes_guides$gene_id, ~calc_inst_effect_h5X(.x, .y, hfile_sc[['X']], X_ntc, obs$gene_transcript, var$gene_id)) %>% list_rbind()
```


```{r}
guide_effects <- guide_effects %>% mutate(Z = inst_effect/inst_se, p = pt(Z, df = n-2), p_adj = p.adjust(p, method='fdr')) %>%
  arrange(target, p_adj) %>% filter(!duplicated(target)) %>%
  left_join(select(var, gene_id, cv), by = c("target" = "gene_id"))
keep_guides <- filter(guide_effects, p_adj < 0.0001, cv < 0.9)
# Reorder to match the order the variables appear in the hfile, prevents us from having to do this every time later.
keep_guides <- keep_guides[match(var$gene_id[var$gene_id %in% keep_guides$target], keep_guides$target), ]
```


```{r}
# Example of using new code to do a CV iteration.
folds <- createFolds(obs$gene_transcript, k=5)

train_obs <- !(1:length(obs$gene_transcript) %in% folds$Fold1)
train_obs <- train_obs & (obs$gene_id %in% c(keep_guides$target, ntc))
train_ntc <- train_obs[cells_ntc]

inst_effects <- map2(keep_guides$inst_id, keep_guides$target, ~ multiple_iv_reg_h5X(.x, .y, hfile_sc[['X']], X_ntc[,train_ntc], obs$gene_transcript, var$gene_id, keep_guides$target, train_obs)) %>% list_rbind()

beta_obs <- inst_effects$beta_obs
names(beta_obs) <- inst_effects$inst_id
R_hat <- data.matrix(select(inst_effects, ends_with('beta_hat')) %>% rename_with(~sub('_beta_hat', '', .x)))
SE_hat <- data.matrix(select(inst_effects, ends_with('se_hat')) %>% rename_with(~sub('_se_hat', '', .x)))
filtered <- filter_tce(R_hat, SE_hat, max_R = 1.5)
R_hat <- filtered$R
SE_hat <- filtered$SE
rownames(R_hat) <- inst_effects$inst_id
rownames(SE_hat) <- inst_effects$inst_id

weights <- inspre::make_weights(SE_hat, max_med_ratio = 50)
fit_res <- fit_inspre(R_hat, W = weights, verbose = 2, cv_folds = 0, ncores = 8, warm_start = FALSE, lambda = 0.96, its=50, rho=100, tau=1.5, mu=10)
```


```{r}
test_obs <- (1:length(obs$gene_transcript) %in% folds$Fold1)
test_obs <- test_obs & (obs$gene_id %in% c(keep_guides$target, ntc))

pred_res <- predict_inspre_inv_h5X(fit_res, hfile_sc[['X']], beta_obs, obs$gene_transcript, var$gene_id, keep_guides$target, test_obs)
```
