```{r}
require(pcalg)
require(foreach)
require()
```

```{r}
run_sim <- function(iter, D, N_cont, N_int, DAG){
  dataset <- generate_dataset(D, N_cont, N_int, DAG = DAG)
  write.table(dataset$Y, file=paste0("data_", iter, ".txt"), row.names=FALSE)
  write.table(dataset$targets, file=paste0("targets_", iter, ".txt"), col.names=FALSE, row.names=FALSE)
  write.table(dataset$G, file=paste0("G_true_", iter, ".txt"))
  
  methods <- c("inspre", "PC", "GIES", "LINGAM")
  time_frame <- data.frame(time=rep(0, length(methods)), row.names=methods)
  
  for(method in methods){
    D_hat = NULL
    lambda = NULL
    start_time <- Sys.time()
    
    if(method == "inspre"){
      inspre_res <- fit_inspre_from_X(dataset$Y, dataset$targets, cv_folds=5, verbose=0, lambda_min_ratio = 0.01, nlambda = 10)
      index <- which.min(inspre_res$eps_hat_G)
      G_hat <- inspre_res$R_hat[,,index]
    } else if(method == "PC"){
      suff_stat <- list(C = cor(dataset$Y), n = nrow(dataset$Y))
      pc_res <- pcalg::pc(suff_stat, indepTest = pcalg::gaussCItest,
                          labels = colnames(dataset$Y), alpha = 0.01)
      G_hat <- as(pc_res@graph, "matrix")
    } else if(method == "GIES"){
      gies_res <- pcalg::gies(dataset_to_score(dataset))
      G_hat <- as(gies_res$essgraph, "matrix")
      rownames(G_hat) <- paste0("V", 1:D)
      G_hat <- G_hat + 0.0
    } else if(method == "LINGAM"){
      lingam_res <- pcalg::lingam(dataset$Y)
      G_hat <- t(lingam_res$Bpruned)
      rownames(G_hat) <- paste0("V", 1:D)
    }
    run_time <- as.numeric(difftime(Sys.time(), start_time, units="secs"))
    time_frame[method, "time"] = run_time
    write.table(G_hat, file=paste0("G_", method, " _", iter, ".txt"))
  }
  write.table(time_frame, file=paste0("times_", iter, ".txt"))
}
```


```{r}
n_iter <- 10
D <- 10
N_cont <- 1000
N_int <- 100
DAG <- TRUE

run_sim(1, D, N_cont, N_int, DAG)
```

