# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fit lasso model (one iteration)
#'
#' Minimize .5 || Y - XB ||^2_2 + gamma |B|_1
#'
#' @param X NxP matrix of covariates
#' @param Y N-vector of response
#' @param B P-vector of coefficents (to be updated)
#' @param lambda P-vector L1 regulation coeffs
#' @export
lasso_one_iteration <- function(X, Y, B, lambda) {
  .Call(`_inspre_lasso_one_iteration`, X, Y, B, lambda)
}
