# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fit lasso model (one iteration)
#'
#' Minimize .5 || Y - XB ||^2_2 + gamma |B|_1
#'
#' @param X NxP matrix of covariates.
#' @param Y N-vector of response.
#' @param B P-vector of coefficents (to be updated).
#' @param lambda P-vector L1 regulation coeffs.
#' @param niter Integer, number of lasso iterations to perform.
#' @export
lasso <- function(X, Y, B, lambda, niter) {
    .Call(`_inspre_lasso`, X, Y, B, lambda, niter)
}

